FIX: Fix missing std::string declaration
src/slic3r/GUI/DeviceCore/DevLamp.h:22:41: error: ‘string’ in namespace ‘std’ does not name a type
   22 |         void SetChamberLight(const std::string& status);
      |                                         ^~~~~~

(cherry picked from commit abd986164785070dcd39204781a0e5a9d40ce216)